apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: desafio-devops-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: paulofabianoo/desafio-devops-java:latest
        name: jenkins-jmx
        ports:
          - name: web
            containerPort: 8080
            protocol: TCP
          - name: tomcat-metrics
            containerPort: 9404
            protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 2Gi
        imagePullPolicy: IfNotPresent
        startupProbe:
          httpGet:
            port: web
            path: /jenkins/health/
            scheme: HTTP  
          failureThreshold: 18
          periodSeconds: 10
        readinessProbe:
          httpGet: 
            port: web
            path: /jenkins/health/
            scheme: HTTP  
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet: 
            port: web
            path: /jenkins/health/
            scheme: HTTP    
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 2
        env:
          - name: JENKINS_PREFIX
            value: /jenkins
          - name: JENKINS_HOME
            value: /var/jenkins_home
          - name: JAVA_TOOL_OPTIONS
            valueFrom:
              configMapKeyRef:
                key: JAVA_TOOL_OPTIONS
                name: jmx-exporter-config
        volumeMounts:
          - name: jenkins-storage
            mountPath: /var/jenkins_home
          - name: tomcat-metrics
            mountPath: /opt/jmx_exporter/config.yaml
            subPath: config.yaml
      volumes:
        - name: jenkins-storage
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: tomcat-metrics
          configMap:
            name: jmx-exporter-config
            items:
              - key: config.yaml
                path: config.yaml