apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: jenkins-ingress
  namespace: desafio-devops-java
spec: 
  rules:
    - host: jenkins.192.168.122.22.nip.io
      http:
        paths:
          - path: /jenkins
            pathType: Prefix
            backend:
              service:
                name: jenkins-svc
                port: 
                  number: 8080