apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: desafio-devops-java
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9404" 
      prometheus.io/path: "/metrics" 
spec:
  selector:
    app: jenkins
  ports:
    - port: 8080
      name: web
      targetPort: 8080
      protocol: TCP
    - port: 8778
      name: jolokia-metrics
      targetPort: 8778
      protocol: TCP
    - port: 9404
      name: metrics
      targetPort: 9404
      protocol: TCP
  type: ClusterIP