apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: grafana-ing
  namespace: grafana
spec: 
  rules:
    - host: grafana.192.168.122.22.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-svc
                port: 
                  number: 3000